baseURL = 'https://dudung.github.io/slide-lib'
languageCode = 'en-us'
title = 'slide-lib'
theme = 'default'

ignoreErrors = ['error-missing-instagram-accesstoken']

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

[[menu.main]]
  name = 'Home'
  weight = 3
  identifier = 'home'
  url = '/'

[[menu.main]]
  name = 'Tags'
  weight = 2
  identifier = 'tags'
  url = '/tags'

[[menu.main]]
  name = 'Cats'
  weight = 1
  identifier = 'categories'
  url = '/categories'
